### ISSUE TITLE
Could not install project

### ISSUE THREAD

**Issue by PereViader** [Damarcreative/rem-wm#1]
Hello,

It seems I got some sort of issue while installing the requirements
Any help will be really appreciated 🙏 

```
$ pip install -r requirements.txt
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python312\Lib\site-packages)
Collecting opencv-python==4.6.0.66 (from -r requirements.txt (line 1))
  Downloading opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl.metadata (18 kB)
Collecting pytest==7.1.3 (from -r requirements.txt (line 2))
  Downloading pytest-7.1.3-py3-none-any.whl.metadata (7.7 kB)
Collecting torch==2.2.0 (from -r requirements.txt (line 3))
  Downloading torch-2.2.0-cp312-cp312-win_amd64.whl.metadata (26 kB)
Collecting pydantic==1.10.2 (from -r requirements.txt (line 4))
  Downloading pydantic-1.10.2-py3-none-any.whl.metadata (140 kB)
Collecting loguru==0.6.0 (from -r requirements.txt (line 5))
  Downloading loguru-0.6.0-py3-none-any.whl.metadata (21 kB)
Collecting tqdm==4.64.1 (from -r requirements.txt (line 6))
  Downloading tqdm-4.64.1-py2.py3-none-any.whl.metadata (57 kB)
Collecting Pillow==9.2.0 (from -r requirements.txt (line 7))
  Downloading Pillow-9.2.0.tar.gz (50.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 MB 88.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffusers==0.4.2 (from -r requirements.txt (line 8))
  Downloading diffusers-0.4.2-py3-none-any.whl.metadata (25 kB)
Collecting transformers (from -r requirements.txt (line 9))
  Downloading transformers-4.46.2-py3-none-any.whl.metadata (44 kB)
Collecting scikit-image==0.19.3 (from -r requirements.txt (line 10))
  Downloading scikit-image-0.19.3.tar.gz (22.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.2/22.2 MB 100.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\operations\prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\distributions\sdist.py", line 126, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_internal\utils\misc.py", line 701, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\perev\AppData\Roaming\Python\Python312\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\perev\AppData\Local\Temp\pip-build-env-bp6xehms\overlay\Lib\site-packages\setuptools\__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
```

**Comment by Programmer-0-0** [comment]
This is a bit late but hopefully this will help new people who might face similar issues (also related to #3).

The problem in summary is the python version, this won't work on python 3.12 so we need to downgrade to python 3.10

Now best solution to this is to use Conda, I recommend you install it if you haven't already:
https://www.anaconda.com/download/success (I'm using Miniconda which is the light-weight version)

(Note: don't forget to add conda to PATH if you're on windows)

Conda will allow us to create a virtual environment using any python version (in our case we want 3.10)

inside the root directory of the repo create a new file called **environment.yml**
```name: myenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pip:
      - opencv-python==4.6.0.66
      - pytest==7.1.3
      - pydantic==1.10.2
      - loguru==0.6.0
      - tqdm==4.64.1
      - Pillow==9.2.0
      - diffusers==0.32.2
      - transformers
      - scikit-image==0.19.3
      - gradio
      - timm
```

then run these commands in order:
```
conda env create -f environment.yml
conda activate myenv
pip install einops
```

That's it, should work now, edit the example.py and test it!

**Comment by JohnnyGuitar42** [comment]
> conda env create -f environment.yml

C:\Users\Admin\rem-wm>conda activate bestrem-wm

(bestrem-wm) C:\Users\Admin\rem-wm>python example.py
Traceback (most recent call last):
  File "C:\Users\Admin\rem-wm\example.py", line 1, in <module>
    from remwm import WatermarkRemover
  File "C:\Users\Admin\rem-wm\remwm.py", line 1, in <module>
    import torch
  File "C:\Users\Admin\miniconda3\envs\bestrem-wm\lib\site-packages\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Users\Admin\miniconda3\envs\bestrem-wm\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

i keep getting this error :(
